# Generated by Django 4.0.2 on 2025-06-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_movie_genres_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, to='db.Actor'),
        ),
    ]
